---
- hosts: localhost
  become: true
  gather_facts: false
  vars:
    sudoers:
      - user2
      - user3
  tasks:
    - name: create 'superusers' group
      group:
        name: superusers
        state: present

    - name: Allow 'superusers' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%superusers'
        insertafter: '^%admin'
        line: '%superusers ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to superusers group
      user:
        name: "{{ item }}"
        groups: superusers
        append: yes
      with_items: "{{ sudoers }}"
