---
# handlers file for nginx+php-fpm
- name: restart-nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: restart-php
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted
